apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sqhr8w3iu-java-quarkus
  janus-idp.io/tekton: sqhr8w3iu-java-quarkus
  backstage.io/kubernetes-id: sqhr8w3iu-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sqhr8w3iu-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
